version: '2.1'

services:
  rabbit:
    build: ./config/
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672" 

  pg:
    ports:
      - "5432:5432"
    image: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"    
  
  db:
    build: .
    command: ["python", "message_db.py"] 
    volumes:
      - .:/backend/
    depends_on:
      - rabbit
      - pg
      - redis
    links:
      - rabbit
      - pg
      - redis

  web:
    build: .
    command: ["python", "web_service.py"] 
    ports:
      - "8080:8080"
    volumes:
      - .:/backend/
    depends_on:
      - rabbit
      - pg
      - redis
    links:
      - rabbit
      - pg
      - redis

  crawler:
    build: .
    command: ["python", "crawler_service.py"] 
    volumes:
      - .:/backend/
    depends_on:
      - rabbit
      - pg
      - redis
    links:
      - rabbit
      - pg
      - redis

